package io.springpragmaticpractices.chapter.forteen.three;

import io.springpragmaticpractices.chapter.forteen.User;
import io.springpragmaticpractices.chapter.forteen.UserRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeUserRepository implements UserRepository {

    private final long autoGeneratedId = 0;
    private final List<User> data = new ArrayList<>();

    @Override
    public Optional<User> findByEmail(long id) {
        return data.stream().filter(item -> item.getId().equals(id)).findAny();
    }

    @Override
    public User save(User user) {
        if (user.getId() == null || user.getId() == 0) {
            // create 동작
            User newUser = User.builder()
                    .id(++autoGeneratedId)
                    .email(user.getEmail())
                    .nickname(user.getNickname())
                    .address(user.getAddress())
                    .verificationCode(user.getVerificationCode())
                    .status(user.getStatus())
                    .lastLoginAt(user.getLastLoginAt())
                    .build();

            data.add(newUser);
            return newUser;
        } else {
            // update 동작
            data.removeIf(item -> item.getId() == user.getId());
            data.add(user);
            return user;
        }
    }
}
